# Makefile for OU4
# DOA LP4 2020
#
# Useage:
# make 			- compile all binaries
# make clean		- clean all binaries 
# make memtest		- test for memory leaks with valgrind

EXE = tabletest

SRC = ../datastructures-v1.0.8.2


